openapi: 3.0.0
  
info:
  title: Tillit OLX API
  version: '1'
  description: 
    '
    <a href="https://storage.googleapis.com/assets.tillit.eu/media/pdfs/Tillit-Tech-Overview-OLX.pdf">
    <img height="200" src="https://storage.googleapis.com/assets.tillit.eu/media/images/Tillit-Tech-Overview-OLX.png"/>
    </div>
    <br/>
    Technical integration - Overview
    </a>
    '
  
  
servers:
  - url: https://dev.tillit.eu/api/olx
  - url: https://www.tillit.eu/api/olx
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
paths:
  /insurance/create:
    post:
      tags:
        - Insurance
      summary: Create insurance
      description: Endpoint for activating the insurance. Should be called when a purchase is made. All prices are stated in zł.
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            example: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni
          required: true
      requestBody:
        description: All prices are stated in zł.
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_id:
                  maximum: 64
                  type: string
                  example: UUID
                  description: Common UUID for insurance.
                ad:
                  type: object
                  required:
                    - item_value
                    - ad_code
                    - ad_url
                    - ad_details
                  properties:
                    item_value:
                      type: number
                      example: 240
                      description: The price the customer paid for the item.
                    asking_price:
                      type: number
                      nullable: true
                      example: 250
                      description: The original price the item was advertised for.
                    ad_code:
                      type: string
                      example: "601924026"
                    ad_url:
                      type: string
                      example: "https://www.olx.pl/d/oferta/iphone-15-pro-max-256-gb-CID99-ID16sdMt.html"
                    ad_details:
                      type: array
                      example:
                        - name: title
                          text: "iphone-15-pro-max-256-gb"
                        - name: category
                          text: "Smartfony i telefony komórkowei"
                        - name: sub_category
                          text: "Electronics"
                        - name: description
                          text: "W zestawie telefon, pudełko, etui z magsafe, etui z magsafe na smyczy, dwa nowe szkła prywatyzujące z adapterem do łatwiejszej aplikacji."
                        - name: ad_image_1
                          text: https://example.com/images/image1.jpg
                        - name: ad_image_2
                          text: https://example.com/images/image2.jpg
                        - name: other
                          text: "example example example"
                      items:
                        type: object
                        required:
                          - name
                          - text
                        properties:
                          name:
                            type: string
                            description: "[title,description,category,size,tags,condition,...]"
                          text:
                            type: string
                purchase:
                  type: object
                  required:
                    - shipping_price
                    - payment_fee
                    - products
                  properties:
                    shipping_price:
                      type: number
                      example: 5.99
                      description: Shipping price in zł
                    payment_fee:
                      type: number
                      example: 15
                      description: Payment fee in zł
                    products:
                      type: array
                      example:
                        - name: 14_DAYS_WARRANTY
                          premium: 12
                      items:
                        type: object
                        required:
                          - name
                          - premium
                        
                        properties:
                          name:
                            type: string
                            description: "[14_DAYS_WARRANTY]"
                          premium:
                            type: number
                            description: Insurance premium in zł
                shipping:
                  type: object
                  required:
                    - supplier
                    - tracking_number
                    - first_name
                    - last_name
                    - phone_number
                    - address
                  properties:
                    supplier:
                      type: string
                      example: "Post Supplier"
                    tracking_number:
                      type: string
                      example: "70722150972118079"
                    first_name:
                      type: string
                      example: "First name"
                    last_name:
                      type: string
                      example: "Last name"
                    phone_number: 
                      type: string
                      example: "+4700000000"
                    address:
                      type: object
                      required:
                        - address_line_1
                        - city
                        - zip_code
                      properties:
                        address_line_1:
                          type: string
                          example: "Address address"
                        city:
                          type: string
                          example: "City"
                        zip_code:
                          type: string
                          example: "20121"
                        province:
                          type: string
                          example: "Province"
                        region:
                          type: string
                          example: "Region"
                        country:
                          type: string
                          example: "Country"
                customer:
                  type: object
                  required:
                    - user_id
                    - email
                  properties:
                    user_id:
                      maximum: 64
                      type: string
                      description: Unique ID for user.
                    email:
                      type: string
                      example: "example@example.example"
                    first_name:
                      nullable: true
                      type: string
                      example: "First Name"
                    last_name:
                      nullable: true
                      type: string
                      example: "Last name"
                    phone_number:
                      nullable: true
                      type: string
                      example: "+4700000000"
              required:
                - transaction_id
                - shipping
                - customer
                - purchase
                - item
                - ad
      responses:
        '201':
          description: Created
        '200':
          description: An insurance with this transaction_id already exists
        '400':
          content:
            application/json:
              schema:
                type: string
                example: descriptive message
          description: Descriptive message
  /{transaction_id}/event:
    post:
      tags:
        - Insurance
      summary: Post event
      description: Used for cancelling insurance or to set the warranty insurance to active.
    
          - **CANCEL_INSURANCE** When an insurance must be cancelled. Can only be called once.
          
          - **START_WARRANTY** When the warranty insurance should be marked as active. Can only be called once. 
      parameters:
        - in: path
          name: transaction_id
          schema:
            type: string
            example: string
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
            example: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - event
                - description
              properties:
                event:
                  description:
                    '[CANCEL_INSURANCE, START_WARRANTY]'
                  type: string
                  example: "CANCEL_INSURANCE"
                description:
                  type: string
                  maximum: 1000
                  example: "Package was never sent by seller."
      responses:
        '200':
          description: OK / The warranty insurance has already been marked as started / Insurance has already been cancelled
        '400':
          content:
            application/json:
              schema:
                type: string
                example: No insurance with this transaction_id exists
          description: Descriptive message
  /{transaction_id}/claim_url:
    get:
      tags:
        - Claim
      summary: Get claim URL
      description: Endpoint for getting a link to the claim form. Must be called in order to redirect the customer to Tillit claim form.
      parameters:
        - in: path
          name: transaction_id
          schema:
            type: string
            example: string
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
            example: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: https://dev.tillit.eu/sesame/login/?sesame=AAAAdgW70nQJJDzWoa1LulSK&next=/users/shipping_claim/?insurance_id=12
        '400':
          content:
            application/json:
              schema:
                type: string
                example: The provided transaction_id does not exist
          description: Descriptive message
  /{transaction_id}/claim_url/ks:
    get:
      tags:
        - Claim
      summary: Get claim URL for customer service
      description: Endpoint for getting a link to the claim form as marketplace customer service. Must be called in order to redirect the customer service user to Tillit claim form.
      parameters:
        - in: path
          name: transaction_id
          schema:
            type: string
            example: string
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
            example: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: https://dev.tillit.eu/sesame/login/?sesame=AAAAdgW70nQJJDzWoa1LulSK&next=/users/shipping_claim/?insurance_id=12
        '400':
          content:
            application/json:
              schema:
                type: string
                example: The provided transaction_id does not exist
          description: Descriptive message
